name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build Cargo
      run: cargo build
      working-directory: decryption-mlm-wasm
    - name: Add wasm target
      run: |
          rustup target add wasm32-unknown-unknown
    - name: Build WASM
      run: wasm-pack build --target web --out-dir ../decryption-mlm-vue3/pkg
      working-directory: decryption-mlm-wasm

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: decryption-mlm-vue3/package-lock.json
    - name: npm install
      run: npm install
      working-directory: decryption-mlm-vue3
    - name: build Vue
      run: npm run build
      working-directory: decryption-mlm-vue3
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: decryption-mlm-vue3/dist
            
